M48
; DRILL file {KiCad (6.0.10)} date Thu Feb 23 16:05:41 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-23T16:05:41-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0598
%
G90
G05
T1
X5.5Y-4.2
X5.6Y-4.3468
X5.8Y-4.1
X5.8Y-4.2
X5.8Y-4.3
X5.9Y-3.8
X6.1Y-4.2
X6.2Y-4.0
T2
X5.9Y-3.6
X6.1Y-3.6
T0
M30
